"""
BOP-NoIPCA - Master Orchestration Script

Runs the complete workflow for a range of panel identifiers:
1. Generate panel data
2. Calculate SDF moments
3. Compute Fama factors
4. Compute DKKM factors for multiple feature counts

Usage:
    python main.py [model] [start] [end] [--koyeb]

Arguments:
    model: Model name (bgn, kp14, gs21) - case insensitive
    start: Starting index (optional, default: 0)
    end: Ending index (optional, default: 1)
    --koyeb: Configure for Koyeb deployment (N_JOBS=24, TEMP_DIR=DATA_DIR)
             Default: jgsrc1 settings (N_JOBS=10, TEMP_DIR=/opt/scratch/keb7)

    Runs workflow for panel_id in range(start, end)
    S3 uploads happen automatically if S3 environment variables are configured

Examples:
    python main.py bgn                    # Runs for index 0 (jgsrc1: N_JOBS=10)
    python main.py bgn 0 5                # Runs for indices 0-4 (jgsrc1: N_JOBS=10)
    python main.py kp14 0 10 --koyeb      # Runs for indices 0-9 (Koyeb: N_JOBS=24)

Output:
    All output is logged to: logs/{model}_{start}_{end}.log
"""

import sys
import os
import subprocess
import time
import pickle
from datetime import datetime
import uuid
import config
from config import (DATA_DIR, N_DKKM_FEATURES_LIST,
                    KEEP_PANEL, KEEP_MOMENTS, KEEP_FACTOR_DETAILS,
                    N, T, BGN_BURNIN, KP14_BURNIN, GS21_BURNIN)
from utils.upload_to_aws import upload_file, is_s3_configured


def create_temp_config(model, start, end, use_koyeb=False):
    """
    Create a temporary config file with optional overrides.

    Args:
        model: Model name (bgn, kp14, gs21)
        start: Starting index
        end: Ending index
        use_koyeb: If True, set N_JOBS=24 for Koyeb deployment (default: N_JOBS=10 for jgsrc1)

    Returns:
        Tuple of (config_module_name, config_file_path)
    """
    # Generate unique config ID
    config_id = f"{model}_{start}_{end}_{uuid.uuid4().hex[:8]}"
    config_module_name = f"temp_config_{config_id}"
    config_file_path = os.path.join(os.path.dirname(__file__), f"{config_module_name}.py")

    # Default to jgsrc1 settings, override for Koyeb
    n_jobs = 24 if use_koyeb else 10
    temp_dir = config.DATA_DIR if use_koyeb else '/opt/scratch/keb7'

    # Create temp config file content
    config_content = f'''"""
Temporary configuration file for {model} workflow (indices {start}-{end})
Auto-generated by main.py
"""

import numpy as np
import os

# =============================================================================
# PANEL DIMENSIONS
# =============================================================================
N = {config.N}
T = {config.T}
BGN_BURNIN = {config.BGN_BURNIN}
KP14_BURNIN = {config.KP14_BURNIN}
GS21_BURNIN = {config.GS21_BURNIN}
N_JOBS = {n_jobs}  # Koyeb: 24, jgsrc1: 10
NUMBA_NUM_THREADS = {config.NUMBA_NUM_THREADS}  # Numba threads per job

# =============================================================================
# DATA DIRECTORY CONFIGURATION
# =============================================================================
_CONFIG_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(_CONFIG_DIR, 'outputs')
TEMP_DIR = {repr(temp_dir)}  # Koyeb: DATA_DIR, jgsrc1: /opt/scratch/keb7

os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(TEMP_DIR, exist_ok=True)

# =============================================================================
# FILE MANAGEMENT FLAGS
# =============================================================================
KEEP_PANEL = {config.KEEP_PANEL}
KEEP_MOMENTS = {config.KEEP_MOMENTS}
KEEP_FACTOR_DETAILS = {config.KEEP_FACTOR_DETAILS}

# =============================================================================
# DKKM AND FAMA PARAMETERS
# =============================================================================
INCLUDE_MKT = {config.INCLUDE_MKT}
NMAT = {config.NMAT}
N_DKKM_FEATURES_LIST = {config.N_DKKM_FEATURES_LIST}
DKKM_RANK_STANDARDIZE = {config.DKKM_RANK_STANDARDIZE}
ALPHA_LST_FAMA = {config.ALPHA_LST_FAMA}
ALPHA_LST = {config.ALPHA_LST}
ALPHA_LST_GS = {config.ALPHA_LST_GS}
STDZ_FM = {config.STDZ_FM}

# =============================================================================
# MODEL CHARACTERISTICS AND FACTOR NAMES
# =============================================================================
CHARS_DEFAULT = {config.CHARS_DEFAULT}
FACTOR_NAMES_DEFAULT = {config.FACTOR_NAMES_DEFAULT}
CHARS_GS21 = {config.CHARS_GS21}
FACTOR_NAMES_GS21 = {config.FACTOR_NAMES_GS21}

# =============================================================================
# BGN Model Parameters
# =============================================================================
PI = {config.PI}
RBAR = {config.RBAR}
KAPPA = {config.KAPPA}
SIGMA_R = {config.SIGMA_R}
BETA_ZR = {config.BETA_ZR}
SIGMA_Z = {config.SIGMA_Z}
CBAR = {config.CBAR}
CHAT = np.exp(CBAR)
I = {config.I}
GAMMA_GRID = np.arange(0.5, 1.1, 0.1)

# =============================================================================
# KP14 Model Parameters
# =============================================================================
KP14_DT = {config.KP14_DT}
KP14_MU_X = {config.KP14_MU_X}
KP14_MU_Z = {config.KP14_MU_Z}
KP14_SIGMA_X = {config.KP14_SIGMA_X}
KP14_SIGMA_Z = {config.KP14_SIGMA_Z}
KP14_THETA_EPS = {config.KP14_THETA_EPS}
KP14_SIGMA_EPS = {config.KP14_SIGMA_EPS}
KP14_THETA_U = {config.KP14_THETA_U}
KP14_SIGMA_U = {config.KP14_SIGMA_U}
KP14_DELTA = {config.KP14_DELTA}
KP14_MU_LAMBDA = {config.KP14_MU_LAMBDA}
KP14_SIGMA_LAMBDA = {config.KP14_SIGMA_LAMBDA}
KP14_MU_H = {config.KP14_MU_H}
KP14_MU_L = {config.KP14_MU_L}
KP14_LAMBDA_H = {config.KP14_LAMBDA_H}
KP14_LAMBDA_L = {config.KP14_LAMBDA_L}
KP14_R = {config.KP14_R}
KP14_GAMMA_X = {config.KP14_GAMMA_X}
KP14_GAMMA_Z = {config.KP14_GAMMA_Z}
KP14_ALPHA = {config.KP14_ALPHA}
KP14_PROB_H = {config.KP14_PROB_H}
KP14_CONST = {config.KP14_CONST}
KP14_A_0 = {config.KP14_A_0}
KP14_A_1 = {config.KP14_A_1}
KP14_A_2 = {config.KP14_A_2}
KP14_A_3 = {config.KP14_A_3}
KP14_RHO = {config.KP14_RHO}
KP14_C = {config.KP14_C}

# =============================================================================
# GS21 Model Parameters
# =============================================================================
GS21_BETA = {config.GS21_BETA}
GS21_PSI = {config.GS21_PSI}
GS21_GAMMA = {config.GS21_GAMMA}
GS21_G = {config.GS21_G}
GS21_ALPHA = {config.GS21_ALPHA}
GS21_DELTA = {config.GS21_DELTA}
GS21_RHO_X = {config.GS21_RHO_X}
GS21_SIGMA_X = {config.GS21_SIGMA_X}
GS21_XBAR = {config.GS21_XBAR}
GS21_RHO_Z = {config.GS21_RHO_Z}
GS21_SIGMA_Z = {config.GS21_SIGMA_Z}
GS21_ZBAR = {config.GS21_ZBAR}
GS21_CHI = {config.GS21_CHI}
GS21_TAU = {config.GS21_TAU}
GS21_PHI = {config.GS21_PHI}
GS21_KAPPA_E = {config.GS21_KAPPA_E}
GS21_KAPPA_B = {config.GS21_KAPPA_B}
GS21_ZETA = {config.GS21_ZETA}
GS21_IMIN = {config.GS21_IMIN}
GS21_IMAX = {config.GS21_IMAX}
GS21_R = {config.GS21_R}

# =============================================================================
# MODEL-SPECIFIC MAPPINGS
# =============================================================================
LOADING_KEYS = {config.LOADING_KEYS}
FACTOR_KEYS = {config.FACTOR_KEYS}
MODEL_CHARS = {config.MODEL_CHARS}
MODEL_FACTOR_NAMES = {config.MODEL_FACTOR_NAMES}
MODEL_ALPHA_LST = {config.MODEL_ALPHA_LST}

def get_model_config(model_name):
    """Get configuration dictionary for a specific model."""
    if model_name not in MODEL_CHARS:
        print(f"Error: Unknown model '{{model_name}}'")
        print(f"Valid models: {{list(MODEL_CHARS.keys())}}")
        import sys
        sys.exit(1)

    burnin_map = {{
        'bgn': BGN_BURNIN,
        'kp14': KP14_BURNIN,
        'gs21': GS21_BURNIN
    }}

    return {{
        'model': model_name,
        'N': N,
        'T': T,
        'burnin': burnin_map[model_name],
        'chars': MODEL_CHARS[model_name],
        'factor_names': MODEL_FACTOR_NAMES[model_name],
        'n_jobs': N_JOBS,
        'include_mkt': INCLUDE_MKT,
        'nmat': NMAT,
        'n_dkkm_features_list': N_DKKM_FEATURES_LIST,
        'dkkm_rank_standardize': DKKM_RANK_STANDARDIZE,
        'alpha_lst_fama': ALPHA_LST_FAMA,
        'alpha_lst': MODEL_ALPHA_LST[model_name],
        'stdz_fm': STDZ_FM
    }}
'''

    # Write temp config file
    with open(config_file_path, 'w') as f:
        f.write(config_content)

    print(f"[CONFIG] Created temporary config: {config_module_name}")
    print(f"[CONFIG] N_JOBS = {n_jobs}, TEMP_DIR = {temp_dir}")

    return config_module_name, config_file_path


def run_script(script_name, args, description, config_module=None, env=None):
    """
    Run a Python script and handle errors. Returns elapsed time in seconds.

    Args:
        script_name: Name of the script to run
        args: List of arguments to pass to the script
        description: Description to print
        config_module: Optional config module name to pass via --config
        env: Optional environment variables dict (None = inherit parent environment)
    """
    print(f"\n{'='*70}")
    print(f"{description}")
    print(f"{'='*70}\n")

    cmd = [sys.executable, script_name] + args
    if config_module:
        cmd.extend(['--config', config_module])

    start_time = time.time()
    # Explicitly pass redirected stdout/stderr so subprocess output goes to log file
    result = subprocess.run(cmd, stdout=sys.stdout, stderr=sys.stderr, env=env)
    elapsed = time.time() - start_time

    if result.returncode != 0:
        print(f"\n[ERROR] {script_name} failed with return code {result.returncode}")
        sys.exit(1)

    return elapsed


def cleanup_factor_file(filepath, stats_key):
    """
    Remove all keys from factor pickle file except stats_key.

    Args:
        filepath: Path to pickle file
        stats_key: Key to keep (e.g., 'fama_stats', 'dkkm_stats', 'ipca_stats')
    """
    if not os.path.exists(filepath):
        return

    # Read full pickle
    with open(filepath, 'rb') as f:
        data = pickle.load(f)

    # Keep only stats key
    if stats_key in data:
        original_size = os.path.getsize(filepath) / (1024**2)  # MB
        cleaned_data = {stats_key: data[stats_key]}

        # Overwrite with cleaned data
        with open(filepath, 'wb') as f:
            pickle.dump(cleaned_data, f)

        new_size = os.path.getsize(filepath) / (1024**2)  # MB
        print(f"[CLEANUP] Reduced {os.path.basename(filepath)}: {original_size:.2f} MB -> {new_size:.2f} MB")


def run_workflow_for_index(model, panel_id, config_module=None, temp_config_obj=None):
    """
    Run the complete workflow for a single panel index.

    Args:
        model: Model name (bgn, kp14, gs21)
        panel_id: Panel index
        config_module: Optional config module name to pass to subprocesses
        temp_config_obj: Optional config module object for TEMP_DIR lookups

    Note:
        S3 uploads happen automatically if S3 environment variables are configured.
    """
    full_panel_id = f"{model}_{panel_id}"

    # Use temp_config_obj if provided, otherwise fall back to global config
    cfg = temp_config_obj if temp_config_obj is not None else config

    # Prepare environment for subprocesses
    # Set NUMBA_NUM_THREADS from config to control Numba's parallelism
    # Default: NUMBA_NUM_THREADS=1 to avoid nested parallelism with joblib
    subprocess_env = os.environ.copy()
    subprocess_env['NUMBA_NUM_THREADS'] = str(cfg.NUMBA_NUM_THREADS)
    print(f"[PARALLELISM] Set NUMBA_NUM_THREADS={cfg.NUMBA_NUM_THREADS} (avoid nested parallelism with n_jobs={cfg.N_JOBS})")

    print(f"\n{'='*70}")
    print(f"RUNNING WORKFLOW FOR {full_panel_id.upper()}")
    print(f"{'='*70}")

    # Track timing for each step
    timings = {}

    # Step 1: Generate panel data
    timings['generate_panel'] = run_script(
        "utils/generate_panel.py",
        [model, str(panel_id)],
        f"STEP 1: Generating {model.upper()} panel data (index={panel_id})",
        config_module=config_module,
        env=subprocess_env
    )

    # Upload panel file to S3 (if S3 configured)
    panel_file = os.path.join(cfg.TEMP_DIR, f"{full_panel_id}_panel.pkl")
    upload_file(panel_file)

    # Step 2: Calculate SDF conditional moments
    timings['calculate_moments'] = run_script(
        "utils/calculate_moments.py",
        [full_panel_id],
        "STEP 2: Calculating SDF conditional moments (rp, cond_var, etc.)",
        config_module=config_module,
        env=subprocess_env
    )

    # Upload moments file to S3 (if S3 configured)
    moments_file = os.path.join(cfg.TEMP_DIR, f"{full_panel_id}_moments.pkl")
    upload_file(moments_file)

    # Step 3: Compute Fama factors
    timings['run_fama'] = run_script(
        "utils/run_fama.py",
        [full_panel_id],
        "STEP 3: Computing Fama-French and Fama-MacBeth factors",
        config_module=config_module,
        env=subprocess_env
    )

    # Upload Fama file to S3 (if S3 configured)
    fama_file = os.path.join(DATA_DIR, f"{full_panel_id}_fama.pkl")
    upload_file(fama_file)

    # Clean up Fama file if requested
    if not KEEP_FACTOR_DETAILS:
        fama_file = os.path.join(DATA_DIR, f"{full_panel_id}_fama.pkl")
        cleanup_factor_file(fama_file, 'fama_stats')

    # Step 4: Compute DKKM factors for each feature count
    timings['run_dkkm'] = {}
    for i, nfeatures in enumerate(N_DKKM_FEATURES_LIST, 1):
        timings['run_dkkm'][nfeatures] = run_script(
            "utils/run_dkkm.py",
            [full_panel_id, str(nfeatures)],
            f"STEP 4.{i}: Computing DKKM factors (nfeatures={nfeatures})",
            config_module=config_module,
            env=subprocess_env
        )

        # Upload DKKM file to S3 (if S3 configured)
        dkkm_file = os.path.join(DATA_DIR, f"{full_panel_id}_dkkm_{nfeatures}.pkl")
        upload_file(dkkm_file)

        # Upload DKKM weight matrix to S3 (if S3 configured)
        weight_file = os.path.join(cfg.TEMP_DIR, f"{full_panel_id}_dkkm_{nfeatures}_W.pkl")
        upload_file(weight_file)

        # Clean up DKKM file if requested
        if not KEEP_FACTOR_DETAILS:
            dkkm_file = os.path.join(DATA_DIR, f"{full_panel_id}_dkkm_{nfeatures}.pkl")
            cleanup_factor_file(dkkm_file, 'dkkm_stats')

    # Step 5: Clean up moments and panel files to save disk space
    if not KEEP_MOMENTS:
        moments_file = os.path.join(cfg.TEMP_DIR, f"{full_panel_id}_moments.pkl")
        if os.path.exists(moments_file):
            file_size = os.path.getsize(moments_file) / (1024**3)  # Size in GB
            os.remove(moments_file)
            print(f"\n[CLEANUP] Deleted moments file ({file_size:.2f} GB): {moments_file}")
    else:
        print(f"\n[KEEP] Keeping moments file (KEEP_MOMENTS=True)")

    if not KEEP_PANEL:
        panel_file = os.path.join(cfg.TEMP_DIR, f"{full_panel_id}_panel.pkl")
        if os.path.exists(panel_file):
            file_size = os.path.getsize(panel_file) / (1024**3)  # Size in GB
            os.remove(panel_file)
            print(f"[CLEANUP] Deleted panel file ({file_size:.2f} GB): {panel_file}")
    else:
        print(f"[KEEP] Keeping panel file (KEEP_PANEL=True)")

    # Print summary for this index
    total_time = sum([timings['generate_panel'], timings['calculate_moments'], timings['run_fama']] +
                     list(timings['run_dkkm'].values()))

    print(f"\n{'='*70}")
    print(f"WORKFLOW COMPLETE FOR {full_panel_id.upper()}")
    print(f"{'='*70}")
    print(f"Execution Times:")
    print(f"  1. Generate panel:      {timings['generate_panel']:7.1f}s ({timings['generate_panel']/60:5.1f}min)")
    print(f"  2. Calculate moments:   {timings['calculate_moments']:7.1f}s ({timings['calculate_moments']/60:5.1f}min)")
    print(f"  3. Fama factors:        {timings['run_fama']:7.1f}s ({timings['run_fama']/60:5.1f}min)")
    for i, nfeatures in enumerate(N_DKKM_FEATURES_LIST, 1):
        dkkm_time = timings['run_dkkm'][nfeatures]
        print(f"  4.{i} DKKM (n={nfeatures:4d}):      {dkkm_time:7.1f}s ({dkkm_time/60:5.1f}min)")
    print(f"  {'-'*50}")
    print(f"  Total for {full_panel_id}:  {total_time:7.1f}s ({total_time/60:5.1f}min)")
    print(f"{'='*70}\n")

    return timings


def main():
    """Main orchestration function."""
    overall_start = time.time()

    # Print global parameters FIRST so user can cancel if incorrect
    print("="*70)
    print("BACK-OBER-PRUITT - COMPLETE WORKFLOW")
    print("="*70)
    print(f"Global Parameters:")
    print(f"  N (firms):        {N}")
    print(f"  T (periods):      {T}")
    print(f"  BGN burnin:       {BGN_BURNIN}")
    print(f"  KP14 burnin:      {KP14_BURNIN}")
    print(f"  GS21 burnin:      {GS21_BURNIN}")
    print("="*70)
    print()

    # Parse arguments
    if len(sys.argv) < 2:
        print("ERROR: Model name required")
        print("\nUsage: python main.py [model] [start] [end] [--koyeb]")
        print("  model: bgn, kp14, or gs21 (case insensitive)")
        print("  start: starting index (optional, default: 0)")
        print("  end: ending index (optional, default: 1)")
        print("  --koyeb: configure for Koyeb (N_JOBS=24, TEMP_DIR=DATA_DIR)")
        print("           Default: jgsrc1 (N_JOBS=10, TEMP_DIR=/opt/scratch/keb7)")
        print("\nNote: S3 uploads happen automatically if S3 environment variables are configured")
        print("\nExamples:")
        print("  python main.py bgn                   # Runs for index 0 (jgsrc1)")
        print("  python main.py bgn 0 5               # Runs for indices 0-4 (jgsrc1)")
        print("  python main.py kp14 0 10 --koyeb    # Runs for indices 0-9 (Koyeb)")
        sys.exit(1)

    # Check for --koyeb flag
    use_koyeb = '--koyeb' in sys.argv
    if use_koyeb:
        sys.argv.remove('--koyeb')

    # Get model name (case insensitive)
    model = sys.argv[1].lower()
    valid_models = ['bgn', 'kp14', 'gs21']

    if model not in valid_models:
        print(f"ERROR: Invalid model '{sys.argv[1]}'")
        print(f"Valid models: {', '.join(valid_models)} (case insensitive)")
        sys.exit(1)

    # Get start and end indices
    start = int(sys.argv[2]) if len(sys.argv) > 2 else 0
    end = int(sys.argv[3]) if len(sys.argv) > 3 else 1

    # Validate range
    if start >= end:
        print(f"ERROR: start ({start}) must be less than end ({end})")
        sys.exit(1)

    # Create temporary config file
    config_module, config_file_path = create_temp_config(model, start, end, use_koyeb)

    # Import the temp config module for use in logging
    import importlib
    temp_config = importlib.import_module(config_module)

    # Setup logging
    script_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(script_dir)

    logs_dir = os.path.join(script_dir, 'logs')
    os.makedirs(logs_dir, exist_ok=True)

    log_file = os.path.join(logs_dir, f"{model}_{start}_{end}.log")

    # Redirect stdout and stderr to log file
    print(f"Redirecting output to log file: {log_file}")
    print("(All subsequent output will be written to the log file)")
    print()

    original_stdout = sys.stdout
    original_stderr = sys.stderr

    log_handle = open(log_file, 'w', encoding='utf-8', buffering=1)
    sys.stdout = log_handle
    sys.stderr = log_handle

    try:
        print(f"Started at {datetime.now().strftime('%a %d %b %Y, %I:%M%p')}")
        print()
        print(f"Configuration:")
        print(f"  Model: {model}")
        print(f"  Index range: {start} to {end-1} (inclusive)")
        print(f"  Total runs: {end - start}")
        print(f"  DKKM features: {N_DKKM_FEATURES_LIST}")
        print(f"  N_JOBS: {temp_config.N_JOBS}")
        print(f"  Log file: {log_file}")
        print()
        print(f"Directories:")
        print(f"  DATA_DIR (permanent): {DATA_DIR}")
        print(f"  TEMP_DIR (temporary): {temp_config.TEMP_DIR}")
        if temp_config.TEMP_DIR == DATA_DIR:
            print(f"    (using DATA_DIR for temporary files)")
        else:
            print(f"    (using separate scratch directory)")
        print()

        # Run workflow for each index in range
        all_timings = {}
        failed_indices = []
        for i in range(start, end):
            try:
                all_timings[i] = run_workflow_for_index(model, i, config_module=config_module, temp_config_obj=temp_config)
            except Exception as e:
                failed_indices.append(i)

                # Clean up moments and panel files for failed panel (if they exist)
                if not KEEP_MOMENTS:
                    moments_file = os.path.join(temp_config.TEMP_DIR, f"{model}_{i}_moments.pkl")
                    if os.path.exists(moments_file):
                        file_size = os.path.getsize(moments_file) / (1024**3)  # Size in GB
                        os.remove(moments_file)
                        print(f"\n[CLEANUP] Deleted moments file for failed panel ({file_size:.2f} GB): {moments_file}")

                if not KEEP_PANEL:
                    panel_file = os.path.join(temp_config.TEMP_DIR, f"{model}_{i}_panel.pkl")
                    if os.path.exists(panel_file):
                        file_size = os.path.getsize(panel_file) / (1024**3)  # Size in GB
                        os.remove(panel_file)
                        print(f"[CLEANUP] Deleted panel file for failed panel ({file_size:.2f} GB): {panel_file}")

                print(f"\n{'='*70}")
                print(f"ERROR: Workflow failed for {model}_{i}")
                print(f"{'='*70}")
                print(f"Error: {str(e)}")
                print(f"Continuing to next panel...")
                print(f"{'='*70}\n")

        # Final summary
        overall_elapsed = time.time() - overall_start

        print(f"\n{'='*70}")
        print("ALL WORKFLOWS COMPLETE")
        print(f"{'='*70}")
        print(f"Finished at {datetime.now().strftime('%a %d %b %Y, %I:%M%p')}")
        print()
        print(f"Summary for {model.upper()} indices {start} to {end-1}:")
        print(f"  Total runs: {end - start}")
        print(f"  Successful: {len(all_timings)}")
        print(f"  Failed: {len(failed_indices)}")
        if failed_indices:
            print(f"  Failed indices: {failed_indices}")
        print(f"  Total time: {overall_elapsed:7.1f}s ({overall_elapsed/60:5.1f}min)")
        if all_timings:
            print(f"  Average time per successful run: {overall_elapsed/len(all_timings):7.1f}s ({overall_elapsed/len(all_timings)/60:5.1f}min)")
        print()
        print(f"Output files created in: {DATA_DIR}")
        for i in range(start, end):
            if i in failed_indices:
                print(f"\n  Index {i} ({model}_{i}): FAILED - No output files")
            else:
                full_panel_id = f"{model}_{i}"
                print(f"\n  Index {i} ({full_panel_id}):")
                panel_status = "kept" if KEEP_PANEL else "deleted after use"
                moments_status = "kept" if KEEP_MOMENTS else "deleted after use"
                print(f"    - Panel data: {full_panel_id}_panel.pkl ({panel_status})")
                print(f"    - SDF moments: {full_panel_id}_moments.pkl ({moments_status})")
                print(f"    - Fama factors: {full_panel_id}_fama.pkl")
                for nfeatures in N_DKKM_FEATURES_LIST:
                    print(f"    - DKKM (n={nfeatures}): {full_panel_id}_dkkm_{nfeatures}.pkl")
        print()
        print(f"Log file: {log_file}")
        print(f"{'='*70}")

    finally:
        # Restore stdout/stderr and close log file
        sys.stdout = original_stdout
        sys.stderr = original_stderr
        log_handle.close()

        # Clean up temporary config file
        if os.path.exists(config_file_path):
            os.remove(config_file_path)
            print(f"[CONFIG] Cleaned up temporary config: {config_module}")

    # Print completion message to console
    print(f"\n{'='*70}")
    print("WORKFLOW COMPLETE")
    print(f"{'='*70}")
    print(f"Model: {model.upper()}")
    print(f"Indices: {start} to {end-1}")
    print(f"Successful: {end - start - len(failed_indices)}/{end - start}")
    if failed_indices:
        print(f"Failed indices: {failed_indices}")
    print(f"Total time: {overall_elapsed:.1f}s ({overall_elapsed/60:.1f}min)")
    print(f"Log file: {log_file}")
    print(f"{'='*70}")

    # If running on Koyeb with --koyeb flag, delete the service to stop billing
    if use_koyeb:
        koyeb_app_name = os.environ.get('KOYEB_APP_NAME')
        koyeb_service_name = os.environ.get('KOYEB_SERVICE_NAME')
        koyeb_api_token = os.environ.get('KOYEB_API_TOKEN')

        if koyeb_app_name and koyeb_service_name and koyeb_api_token:
            print(f"\n{'='*70}")
            print("KOYEB SERVICE SHUTDOWN")
            print(f"{'='*70}")
            print(f"Deleting Koyeb service to stop billing...")
            print(f"  App: {koyeb_app_name}")
            print(f"  Service: {koyeb_service_name}")

            try:
                # Use Koyeb CLI to delete the service
                import subprocess
                result = subprocess.run(
                    ['koyeb', 'services', 'delete', koyeb_service_name,
                     '--app', koyeb_app_name,
                     '--token', koyeb_api_token],
                    capture_output=True,
                    text=True
                )

                if result.returncode == 0:
                    print(f"✓ Service deleted successfully")
                    print(f"  Koyeb billing has stopped")
                else:
                    print(f"⚠ Failed to delete service:")
                    print(f"  {result.stderr}")
                    print(f"  Note: You may need to manually delete the service to stop billing")
            except FileNotFoundError:
                print(f"⚠ Koyeb CLI not found")
                print(f"  Cannot automatically delete service")
                print(f"  To stop billing, manually delete the service at:")
                print(f"  https://app.koyeb.com")
            except Exception as e:
                print(f"⚠ Error deleting service: {e}")
                print(f"  To stop billing, manually delete the service at:")
                print(f"  https://app.koyeb.com")

            print(f"{'='*70}")
        else:
            missing = []
            if not koyeb_app_name:
                missing.append('KOYEB_APP_NAME')
            if not koyeb_service_name:
                missing.append('KOYEB_SERVICE_NAME')
            if not koyeb_api_token:
                missing.append('KOYEB_API_TOKEN')

            print(f"\n⚠ Koyeb service shutdown skipped - missing environment variables:")
            print(f"  {', '.join(missing)}")
            print(f"  To stop billing, manually delete the service at:")
            print(f"  https://app.koyeb.com")


if __name__ == "__main__":
    main()
